# importing required libraries
import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [41]:

# importing required libraries
import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [5]:
#load the data
df=pd.read_csv('E:/twitter sent.csv',encoding='latin')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      31962 non-null  int64 
 1   label   31962 non-null  int64 
 2   tweet   31962 non-null  object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB


In [74]:
df.tail()

id  label                                              tweet
31957  31958      0  ate @user isz that youuu?ð??ð??ð??ð??ð??ð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

In [8]:
df.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [10]:
# there is no null values
#so we proceed with splitting the data into train and test data
# using sklearn libraries

In [14]:
#For the normal tweet, it will be 0 and for the racist or sexist tweet, it will be 1
df.label.value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [29]:
# we split into 80 and 20

df_train, df_test = train_test_split (df, test_size = 0.2, stratify = df['label'], random_state=21)

In [33]:
# get the shape of train and test split.
df_train.shape

(25569, 3)

In [34]:
df_test.shape

(6393, 3)

In [35]:
df_train.shape, df_test.shape

((25569, 3), (6393, 3))

In [46]:
#TF-IDF stands for term frequency-inverse document frequency and 
#it is a measure, used in the fields of information retrieval (IR) and machine learning, 
#First, create the object of the TFidfVectorizer, build your model and fit the model with the training data tweets:

In [43]:
# create a TF-IDF vectorizer object
tfidf_vectorizer=TfidfVectorizer(lowercase= True, max_features=1000, stop_words=ENGLISH_STOP_WORDS)

# fit the object with the training data tweets
tfidf_vectorizer.fit(df_train.tweet)

TfidfVectorizer(max_features=1000,
                stop_words=frozenset({'a', 'about', 'above', 'across', 'after',
                                      'afterwards', 'again', 'against', 'all',
                                      'almost', 'alone', 'along', 'already',
                                      'also', 'although', 'always', 'am',
                                      'among', 'amongst', 'amoungst', 'amount',
                                      'an', 'and', 'another', 'any', 'anyhow',
                                      'anyone', 'anything', 'anyway',
                                      'anywhere', ...}))

In [48]:
#Use the model and transform the train and test data tweets:

In [51]:
# transform the train and test data
df_train_idf = tfidf_vectorizer.transform(df_train.tweet)
df_test_idf  = tfidf_vectorizer.transform(df_test.tweet)

In [52]:
df_train_idf 

<25569x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 105309 stored elements in Compressed Sparse Row format>

In [53]:
df_test_idf

<6393x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 26118 stored elements in Compressed Sparse Row format>

In [54]:
#Now, we will create an object of the Logistic Regression model
#ur focus is not on building a very accurate classification model 
#but instead to see how we can deploy this predictive model to get the results

In [57]:
# create the object of LinearRegression Model
model_LR = LogisticRegression()

# fit the model with the training data
model_LR.fit(df_train_idf, df_train.label)

# predict the label on the traning data
predict_train = model_LR.predict(df_train_idf)

# predict the model on the test data
predict_test = model_LR.predict(df_test_idf)

# f1 score on train data
f1_score(y_true= df_train.label, y_pred= predict_train)

0.4888178913738019

In [60]:
#fa score of a test data
f1_score(y_true= df_test.label, y_pred= predict_test)

0.45751633986928114

In [66]:
"""A machine learning pipeline is a way to codify and automate the workflow it takes 
to produce a machine learning model. Machine learning pipelines
consist of multiple sequential steps that do everything from data extraction and 
preprocessing to model training and deployment."""

'A machine learning pipeline is a way to codify and automate the workflow it takes \nto produce a machine learning model. Machine learning pipelines\nconsist of multiple sequential steps that do everything from data extraction and \npreprocessing to model training and deployment.'

In [65]:
#simply pipeline is used for continous data flow into database
#When we use the fit() function with a pipeline object, both steps are executed. Post the model training process,
#we use the predict() function that uses the trained model to generate the predictions.

In [67]:
# define the stages of the pipeline
pipeline = Pipeline(steps= [('tfidf', TfidfVectorizer(lowercase=True,
                                                      max_features=1000,
                                                      stop_words= ENGLISH_STOP_WORDS)),
                            ('model', LogisticRegression())])

In [70]:
# fit the pipeline model with the training data                            
pipeline.fit(df_train.tweet, df_train.label)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=1000,
                                 stop_words=frozenset({'a', 'about', 'above',
                                                       'across', 'after',
                                                       'afterwards', 'again',
                                                       'against', 'all',
                                                       'almost', 'alone',
                                                       'along', 'already',
                                                       'also', 'although',
                                                       'always', 'am', 'among',
                                                       'amongst', 'amoungst',
                                                       'amount', 'an', 'and',
                                                       'another', 'any',
                                                       'anyhow', 'anyone',
           

In [71]:
#Now, we will test the pipeline with a sample tweet

In [76]:
text = ["Godd luck @team India"]

# predict the label using the pipeline
pipeline.predict(text)
# we can see the result 0 since no hated speech

array([0], dtype=int64)

In [77]:
text1=["temple vandalised"]
pipeline.predict(text1)
#hated speech so we get 1

array([1], dtype=int64)

In [78]:
#We have successfully built the machine learning pipeline and we will save this
#pipeline object using the dump function in the joblib library.
#You just need to pass the pipeline object and the file name:

In [80]:
# import joblib
from joblib import dump

# dump the pipeline model or store the pipeline model
dump(pipeline, filename="text_classification.joblib")

['text_classification.joblib']

In [81]:
#It will create a file name “text_classification.joblib“.
#Now, we will open another Python file and use the load function of the joblib library to load the pipeline model.

In [82]:
# import joblib
from joblib import load

# sample tweet text
text = ["Rohith sharma named a new test team captain of  India and Jasprit bumrah named Vice Captain"]

# load the saved pipleine model
pipeline = load("text_classification.joblib")

# predict on the sample tweet text
pipeline.predict(text)

array([0], dtype=int64)

In [83]:
#to get API we need to install tweet API
# we have to save this in API in web application


In [85]:
df[df.label == 1].head(20)

id  label                                              tweet
13    14      1  @user #cnn calls #michigan middle school 'buil...
14    15      1  no comment!  in #australia   #opkillingbay #se...
17    18      1                             retweet if you agree! 
23    24      1    @user @user lumpy says i am a . prove it lumpy.
34    35      1  it's unbelievable that in the 21st century we'...
56    57      1            @user lets fight against  #love #peace 
68    69      1  ð??©the white establishment can't have blk fol...
77    78      1  @user hey, white people: you can call people '...
82    83      1  how the #altright uses  &amp; insecurity to lu...
111  112      1  @user i'm not interested in a #linguistics tha...
114  115      1  @user why not @user mocked obama for being bla...
131  132      1  #people aren't protesting #trump because a #re...
151  152      1  yes it's  when you call #michelleobama a goril...
156  157      1  as the smaller hands show, barry probably lied...
167  168      1  @user @user you point one finger @user million...
192  193      1  you might be a libtard if... #libtard  #sjw #l...
210  211      1  @user take out the #trash america...  - i vote...
232  233      1  if you hold open a door for a woman because sh...
263  264      1  @user this man ran for governor of ny, the sta...
264  265      1  #stereotyping #prejudice  offer no #hope or so...